# Generated by Django 5.1 on 2024-08-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=20, unique=True)),
                ('config_id', models.CharField(max_length=20)),
                ('apply_area', models.CharField(max_length=100)),
                ('apply_player', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('cfg_data', models.TextField()),
            ],
        ),
    ]
